name: Hello-docker-server-prod
on: 
  workflow_dispatch:
jobs:
  hello-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GHCR
        run: 
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: build and push image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          while read line; do
            echo "Building for: $line"
            docker build --build-arg CUSTOMER_NAME=$line -f Dockerfile.helloserver -t ghcr.io/$OWNER/hello:$line .
            docker push ghcr.io/$OWNER/hello:$line
          done < list.txt

