name: Hello-docker-server
on: 
  workflow_dispatch:
jobs:
  hello-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build and don't push image
        run: |
          while read line; do
            docker build --build-arg CUSTOMER_NAME=$line -f Dockerfile.helloserver -t $line .
          done < list.txt
      - name: run hello container
        run: |
            docker run -d -p 8080:80 banna
            sleep 2
            curl http://localhost:8080/welcome